config/routes.rb
Rails.application.routes.draw do

	root 'pages#index'
  devise_for :users
  
  resources :pages, only: [:index]
  
  resources :courses, only: [:index, :show], path: 'cursos' do
    resources :concepts, only: [:show], path: 'conceitos'
  end

  get '/artigos/:id' => 'contents#show', as: 'content'

  get '/admin' => 'admin/admin#index', as: :admin
  namespace :admin do
    resources :courses
    resources :concepts
    resources :contents
  end

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

end

app/views/navbars/_application.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Estuda menino</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "<i class='fa fa-graduation-cap'></i> Cursos".html_safe, courses_path %></li>
        <li><%= link_to "<i class='fa fa-file-code-o'></i> Gist".html_safe, 'https://gist.github.com/', target: '_blank' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Backoffice", admin_path if current_user.admin %></li>
            <li><%= link_to "Meu cadastro", destroy_user_session_path, :method => :delete %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Sair", destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>