config/routes.rb
Rails.application.routes.draw do

	root 'pages#index'
  devise_for :users
  
  resources :pages, only: [:index]
  
  resources :courses, only: [:index, :show], path: 'cursos' do
    resources :concepts, only: [:show], path: 'conceitos'
  end

  get '/artigos/:id' => 'contents#show', as: 'content'

  get '/admin' => 'admin/admin#index', as: :admin
  namespace :admin do
    resources :courses
    resources :concepts
    resources :contents
  end

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

end

app/models/concept.rb
class Concept < ActiveRecord::Base
	# Relations
	belongs_to :user
	belongs_to :course
  has_many :contents, dependent: :destroy

  # Validations
  validates :name, :course_id, presence: true

	# Slug
	def to_param
		"#{id}-#{name.downcase}"
	end

end

app/controllers/admin/concepts_controller.rb
class Admin::ConceptsController < Admin::AdminController
  before_action :set_concept, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @concepts = Concept.all
    respond_with(@concepts)
  end

  def show
    @contents = Content.where(concept_id: @concept.id).order('fiat asc')
    respond_with(@concept)
  end

  def new
    @concept = Concept.new
    respond_with(@concept, location: admin_concepts_path)
  end

  def edit
  end

  def create
    @concept = Concept.new(concept_params)
    @concept.user_id = current_user.id
    @concept.save
    respond_with(@concept, location: admin_concepts_path)
  end

  def update
    @concept.update(concept_params)
    respond_with(@concept, location: admin_concepts_path)
  end

  def destroy
    @concept.destroy
    respond_with(@concept, location: admin_concepts_path)
  end

  private
    def set_concept
      @concept = Concept.find(params[:id])
    end

    def concept_params
      params.require(:concept).permit(:name, :fiat, :user_id, :course_id)
    end
end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController
  before_action :set_concept, only: [:show]

  respond_to :html

  def show
    @contents = Content.where(concept_id: @concept.id).order('fiat ASC')
    @course = Course.find(params[:course_id])
    respond_with(@concept)
  end

  private
    def set_concept
      @concept = Concept.find(params[:id])
    end
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/views/admin/concepts/_form.html.erb
<%= bootstrap_form_for([:admin, @concept]) do |f| %>
  <div class="field">
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.text_field :fiat %>
  </div>
  <div class="field">
    <%= f.collection_select :course_id, Course.all, :id, :name, prompt: true, required: true %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/concepts/edit.html.erb
<%= render 'form' %>

app/views/admin/concepts/index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>User</th>
      <th>Course</th>
      <th>Ordem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concepts.each do |concept| %>
      <tr>
        <td><%= concept.id %></td>
        <td><%= concept.name %></td>
        <td><%= concept.user.try(:name) %></td>
        <td><%= concept.course.try(:name) %></td>
        <td><%= concept.fiat %></td>
        <td><%= link_to 'Show', admin_concept_path(concept) %></td>
        <td><%= link_to 'Edit', edit_admin_concept_path(concept) %></td>
        <td><%= link_to 'Destroy', admin_concept_path(concept), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/concepts/new.html.erb
<%= render 'form' %>

app/views/admin/concepts/show.html.erb
<div class='form-group'>
  <p>
    <strong>Name:</strong>
    <%= @concept.name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @concept.user.try(:email) %>
  </p>

  <p>
    <strong>Course:</strong>
    <%= @concept.course.try(:name) %>
  </p>
</div>

<legend>Conteúdos desse conceito</legend>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>User</th>
      <th>Concept</th>
      <th>Ordem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
    <tr>
      <td><%= content.id %></td>
      <td><%= content.title %></td>
      <td><%= content.user.try(:name) %></td>
      <td><%= content.concept.try(:name) %></td>
      <td><%= content.fiat %></td>
      <td><%= link_to 'Show', admin_content_path(content) %></td>
      <td><%= link_to 'Edit', edit_admin_content_path(content) %></td>
      <td><%= link_to 'Destroy', admin_content_path(content), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>